name: CI
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  base:
    name: Archive Base Case
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case
          path: case30.case
  pwl-gencost:
    name: Archive PWL gencost
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: pwl-gencost
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-pwl_gencost.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-pwl_gencost
          path: case30-pwl_gencost.case
  q-gencost:
    name: Archive Q gencost
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: q-gencost
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-q_gencost.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-q_gencost
          path: case30-q_gencost.case
  dcpf:
    name: Archive DCPF
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dcpf
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-dcpf.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-dcpf
          path: case30-dcpf.case
  acpf:
    name: Archive ACPF
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: acpf
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-acpf.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-acpf
          path: case30-acpf.case
  dcopf:
    name: Archive DCOPF
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dcopf
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-dcopf.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-dcopf
          path: case30-dcopf.case
  acopf:
    name: Archive ACOPF
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: acopf
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-acopf.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-acopf
          path: case30-acopf.case
  dcopf-pwl:
    name: Archive DCOPF PWL gencost
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dcopf-pwl
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-dcopf_pwl_gencost.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-dcopf-pwl
          path: case30-dcopf_pwl_gencost.case
  acopf-pwl:
    name: Archive ACOPF PWL gencost
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: acopf-pwl
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-acopf_pwl_gencost.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-acopf-pwl
          path: case30-acopf_pwl_gencost.case
  acopf-q-gencost:
    name: Archive ACOPF Q gencost
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: acopf-q-gencost
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf case30-acopf_q_gencost.case *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: case-acopf-q-gencost
          path: case30-acopf_q_gencost.case

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions: write-all
    needs: [ base, dcpf ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: case
      - uses: actions/download-artifact@v4
        with:
          name: case-pwl_gencost
      - uses: actions/download-artifact@v4
        with:
          name: case-q_gencost
      - uses: actions/download-artifact@v4
        with:
          name: case-dcpf
      - uses: actions/download-artifact@v4
        with:
          name: case-acpf
      - uses: actions/download-artifact@v4
        with:
          name: case-dcopf
      - uses: actions/download-artifact@v4
        with:
          name: case-acopf
      - uses: actions/download-artifact@v4
        with:
          name: case-dcopf-pwl
      - uses: actions/download-artifact@v4
        with:
          name: case-acopf-pwl
      - uses: actions/download-artifact@v4
        with:
          name: case-acopf-q-gencost

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload base artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30.case
          asset_name: case30-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload PWL gencost artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-pwl_gencost.case
          asset_name: case30-pwl_gencost-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload Q gencost artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-q_gencost.case
          asset_name: case30-q_gencost-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload dcpf artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-dcpf.case
          asset_name: case30-dcpf-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload acpf artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-acpf.case
          asset_name: case30-acpf-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload dcopf artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-dcopf.case
          asset_name: case30-dcopf-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload acopf artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-acopf.case
          asset_name: case30-acopf-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload dcopf PWL artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-dcopf_pwl_gencost.case
          asset_name: case30-dcopf_pwl_gencost-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload acopf PWL artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-acopf_pwl_gencost.case
          asset_name: case30-acopf_pwl_gencost-${{ github.ref_name }}.case
          asset_content_type: application/x-tar

      - name: Upload acopf Q gencost artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./case30-acopf_q_gencost.case
          asset_name: case30-acopf_q_gencost-${{ github.ref_name }}.case
          asset_content_type: application/x-tar